name: Build

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'alist version'
        required: true
        default: 'v3.41.0'
      VERSION-WEB:
        description: 'alist-web version'
        required: true
        default: 'latest'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        if: github.event.inputs.VERSION != 'beta' && github.event.inputs.VERSION != 'main'
        uses: vmactions/freebsd-vm@v1.1.7
        with:
          usesh: true
          prepare: |
            pkg install -y git node go gcc wget bash gawk
          run: | 
            Version=$(wget -qO- -t1 -T2 "https://api.github.com/repos/alist-org/alist-web/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g') >> version
            git clone https://github.com/AlistGo/alist -b $Version
            cd alist/public && wget -q https://github.com/AlistGo/alist-web/releases/${{ github.event.inputs.VERSION-WEB }}/download/dist.tar.gz && tar -xf dist.tar.gz && rm -rf dist.tar.gz
            cd ..
            bash ../compile.sh

      - name: Build Beta
        if: github.event.inputs.VERSION == 'beta' || github.event.inputs.VERSION == 'main'
        uses: vmactions/freebsd-vm@v1.1.7
        with:
          usesh: true
          prepare: |
            pkg install -y git node go gcc wget bash
          run: | 
            git clone https://github.com/AlistGo/alist -b ${{ github.event.inputs.VERSION }}
            cd alist/public && git clone https://github.com/alist-org/web-dist -b dev && cp -r web-dist/dist/* dist && rm -rf web-dist
            cd ..
            bash ../compile.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: alist-FreeBSD
          path: alist/alist

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=${{ github.event.inputs.VERSION }}" >> $GITHUB_OUTPUT
          touch release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: steps.tag.outputs.status == 'success' && github.event.inputs.VERSION != 'beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: alist/alist

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.inputs.VERSION == 'beta' || github.event.inputs.VERSION == 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta
          name: AList Beta Version
          body_path: release.txt
          files: alist/alist

      
